export interface Identity {
  gid_uuid: string;
  gid_name: string;
  type: string;
  status: string;
  created_at: string;
  released_at?: string;
  completed: boolean;
  gid_name_moderation_status: string;
  public_signing_key: string;
  public_encryption_key: string;
  is_private: boolean;
  has_wallet: boolean;
  description?: string;
  display_image_url?: string;
  region_code?: string;
  region_name?: string;
  country_code: string;
  country_name: string;
  state_code?: string;
  state_name?: string;
  metro_code?: string;
  metro_name?: string;
  signup_type?: 'localid' | 'globalid';
  encrypted_signup_challenge?: string;
  profile_picture_verified?: boolean;
  purpose_personal: boolean;
  purpose_professional: boolean;
  purpose_recreational: boolean;
  display_name: string;
}
