name: Docker image

on:
  push:
    tags:
      - verifier-agent@v[0-9]+.[0-9]+.[0-9]+

env:
  REPO_NAME: ghcr.io/${{ github.repository }}/verifier-agent

jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version from tag
        id: extract_version
        run: |
          echo "IMAGE_VERSION=$(echo "${{ github.ref_name }}" | cut -dv -f3)"
          echo "IMAGE_VERSION=$(echo "${{ github.ref_name }}" | cut -dv -f3)"  >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./verifier-agent/node
          push: true
          tags: "${{ env.REPO_NAME }}:${{ env.IMAGE_VERSION }},${{ env.REPO_NAME }}:latest"
          cache-from: type=registry,ref=${{ env.REPO_NAME }}
          cache-to: type=inline
